name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Welcome_message
        run: echo "My first GHA job"

      - name: List files
        run: ls

      - name: Read file
        run: cat README.md
